[package]
name = "merit-cli-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36", features = ["full"] }
async-trait = "0.1.86"
dialoguer = "0.11.0"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0.138"
dotenv = "0.15.0"
